language: node_js
node_js:
- '8'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
sudo: required
addons:
  chrome: stable
script:
- ng build --prod --aot
- ng test
- xvfb-run npm run e2e
deploy:
  provider: heroku
  api_key:
    secure: "teUZiKOSiHPjzqqHCrys4zq+DIzg1thXy2SsjrJZITj/oR7gG6sHSaxmUt0CkC6ETep3kIiAds0h9S5vExFfwKXWaE1KT1ePItMbvD8uk+1ZjGFv4MAQVSe6CuxOae42rw45ggniZ4PHY5p44Ub+K3pjV9qe97HLvt11OcBRycyTtjQhvV+R5r7ZfcLzChyKZoLTMRV90yAX7aBX2FMqXl32WKEqwzg53OV2egSBga9vbhdH6xvZU7EDjbdNDkmjO5o+I3lsFG9il9b0nzHABoqGkMuaQOmUculpVNg2BjH9ZouK5lA6V0xve1t+gUQOdApWy3i9/mb7070DVXCYScNnAa4jnurP3roy1QWkd9wMjHcp4tlgOMmGnaIEhoL6qYMacWKPf5emGQ+USdUr9p3c3KqEL3yGLetW8aJLufgLs0rJAVuc+7CfKeAa1oHUhpBHXbzdgd4SOmC1l2Rvch9flTzkHYjoMrMTToZutyzC03o7bpGC1jfg29OA2XilygxNsauyHxYWsrDM3P6sewR+2c29H3OxlT2+NJ0k5zT5WPN5Ti3Ie1t4ecz+f1EbTEM4ubpJYikI1veLObVeYqdB6rqfyuRVM0RvJZ2Uzb2ubg89AhEPgMYG0RV5g32h1AG8CeuOjbmyF7noX5EoX4M0XuJUj8yU2eOx+hlLfXE="
  app: awesome-tastes-discovery
  local_dir: dist
  on:
    repo: anakis/awesome-tastes-discovery