language: node_js
node_js:
- '8'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
sudo: required
  addons:
  chrome: stable
script:
- ng build --prod --aot
- ng test
- xvfb-run npm run e2e
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  api_key:
    secure: "kUT5qCL+O/BYKx2zvt7QJNP2peFzvNg1iLvB33XiXQTsAHHb/mewWQjTaQHH8x0XRvC2MBJS91yYBJMZNLxIC2ETR7gi3DPgIdP6y88WYJofqYd3bag1mYWibfNB8nn7Rn4IOkWstiVQSPgVdeAlm/njZy7Rfk9yLVDRvf7SS+DIQuEXWR/ezoqWN3mMFPknF5vbdz2hRRsH55tBeKjtpQ6zvKr+IOk+5UGKGrHudNHc2hyYB6ao+J3uoe1IUeexHSOJ5nEZEWVGEANo9ssGjxR+dnW4u2k8/0R9Q6QB1bT9VBHl4fPTMj3n3lZ7Rw5FGmNiGAYizEG4DjCc+Pu/Ijn+E58W65cbRx94kDYPo/6OGXLqZfHuPB/iWIty0lhrmvvxXELz19lZhWYtcBWjzSirFG9FFRHU5w9lsDKPY6KEGYyunYE2W7TxoRitr/L/vT4NGdQ2xO9O65X3ytmTSb67EaIBoHycaBaCGQua3B3+K1czBtmAz2ZhC48NQUwipxet/rxGI9ZyJL0n5hK4bGO+9LrLiBVB9SXqyxtteFIeSA8Fes4axqN6i3SPALgC3p/nOAmdR11knugNnVqWPyY6rEwPnDcYByGnCyujPygzGU3I6GeNRtXL8SY1isaWQUY+7G9RYHJc3xnaMWEfvJmnoHud7VzW4kYAsVLcQY4="
  app: awesome-tastes-discovery
  local_dir: dist
  on:
    repo: anakis/awesome-tastes-discovery